### ISSUE TITLE
你好 代码本地运行好的，但是登录进去列表为空

### ISSUE THREAD

**Issue by xgzl87** [Alvin-Tsai/Chat-Room#1]
![default](https://user-images.githubusercontent.com/12945325/28049852-a42be4f2-662c-11e7-9954-e58694b35c52.png)

**Comment by Alvin-Tsai** [comment]
@xgzl87 
请确认server是一直有在运行的
在这情况下你按leave chat room还能回到登入页面吗?
我亲测是无法的，但你会想说怎能登入到聊天室，这是因为关于进入聊天室与否是简单用state的username去判别

**Comment by xgzl87** [comment]
运行的 
但是Listening port: 3000
$ babel-node --presets es2015 server.js
Listening port: 3000

运行的时候好像是这个http://localhost:5000/socket.io/?EIO=3&transport=polling&t=LqmEcse
在哪里修改？

**Comment by Alvin-Tsai** [comment]
@xgzl87 
有在server.js这个档案修改成你的port吗?
`server.listen(3000, function(err) {
    console.log('Listening port: 3000');
});`

**Comment by xgzl87** [comment]
您好，我app运行在5000啊
serve -s dist
http://localhost:5000

server.listen(3000, function(err) { console.log('Listening port: 3000'); });
这个没有修改啊

**Comment by Alvin-Tsai** [comment]
那你应该要把3000改成5000...要符合你的port，然后可以请问一下你的server是用自己的吗?还是我code理面的server.js
你如果是用你自己的server.js但是是用我产生的code当然会没作用了，我的server.js有socket.io的code
建議可以先測試使用我說明中的Test building files: yarn build-test来测试(预设是3000port)

**Comment by xgzl87** [comment]
好了 谢谢您的解答 是要把3000改成5000。
另外我用的自己的server.js

**Comment by Alvin-Tsai** [comment]
@xgzl87 哈~有解决就好:-)
